package permission

// All 是代码侧注册的**完整权限点清单**：迁移据此 upsert 到 s_permission_point
// （权限点字典由代码注册、后台不可增删 —— docs/01 §8.0.1 硬约束 1）。
//
// ★ 判据①「每个权限点至少被一处代码消费」的消费点即本清单：删掉任一项，
//
//	scripts/check_perm_registry.py 立刻报红（TC-M0-08）。
var All = []Code{
	MdCustomer,
	MdMaterial,
	MdTestItem,
	MdVehicle,
	MdTeam,
	RecvNoticeCreate,
	RecvNoticeEdit,
	RecvArriveConfirm,
	RecvWeigh,
	RecvBagGen,
	RecvLabelPrint,
	RecvLabelReprint,
	RecvReturn,
	SampleTake,
	SampleRetainIn,
	SampleRetainLend,
	SampleRetainDestroyInit,
	SampleRetainDestroyApprove,
	ProdBatchCreate,
	ProdFeedScan,
	ProdFeedCorrect,
	ProdOpLog,
	ProdFgGen,
	ProdRework,
	InspTaskView,
	InspScopeEdit,
	InspResultEntry,
	InspResultCorrect,
	InspFileUpload,
	InspConclusion,
	InspDisposition,
	InspConcessionQcSign,
	InspConcessionDeptSign,
	InspUrgentReleaseInit,
	InspUrgentReleaseApprove,
	ShipLoadScan,
	ShipOutRegister,
	ShipVoidInit,
	ShipVoidApprove,
	TraceForward,
	TraceBackward,
	TraceBatchView,
	ReportGenerate,
	ReportShareManage,
	RptView,
	RptExport,
	SysUserManage,
	SysPermEdit,
	SysAuditView,
	SysCodeRule,
	SysParamEdit,
}
